# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clipper_frontend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clipper_frontend.proto',
  package='clipper.grpc',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x63lipper_frontend.proto\x12\x0c\x63lipper.grpc\"\x1c\n\x0b\x46loatsInput\x12\r\n\x05input\x18\x01 \x03(\x02\"O\n\x0ePredictRequest\x12\x13\n\x0b\x61pplication\x18\x01 \x01(\t\x12(\n\x05input\x18\x02 \x01(\x0b\x32\x19.clipper.grpc.FloatsInput\"!\n\x0fPredictResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2Y\n\x07Predict\x12N\n\rPredictFloats\x12\x1c.clipper.grpc.PredictRequest\x1a\x1d.clipper.grpc.PredictResponse\"\x00\x62\x06proto3')
)




_FLOATSINPUT = _descriptor.Descriptor(
  name='FloatsInput',
  full_name='clipper.grpc.FloatsInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='clipper.grpc.FloatsInput.input', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=68,
)


_PREDICTREQUEST = _descriptor.Descriptor(
  name='PredictRequest',
  full_name='clipper.grpc.PredictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='application', full_name='clipper.grpc.PredictRequest.application', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input', full_name='clipper.grpc.PredictRequest.input', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=149,
)


_PREDICTRESPONSE = _descriptor.Descriptor(
  name='PredictResponse',
  full_name='clipper.grpc.PredictResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='clipper.grpc.PredictResponse.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=184,
)

_PREDICTREQUEST.fields_by_name['input'].message_type = _FLOATSINPUT
DESCRIPTOR.message_types_by_name['FloatsInput'] = _FLOATSINPUT
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['PredictResponse'] = _PREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FloatsInput = _reflection.GeneratedProtocolMessageType('FloatsInput', (_message.Message,), dict(
  DESCRIPTOR = _FLOATSINPUT,
  __module__ = 'clipper_frontend_pb2'
  # @@protoc_insertion_point(class_scope:clipper.grpc.FloatsInput)
  ))
_sym_db.RegisterMessage(FloatsInput)

PredictRequest = _reflection.GeneratedProtocolMessageType('PredictRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTREQUEST,
  __module__ = 'clipper_frontend_pb2'
  # @@protoc_insertion_point(class_scope:clipper.grpc.PredictRequest)
  ))
_sym_db.RegisterMessage(PredictRequest)

PredictResponse = _reflection.GeneratedProtocolMessageType('PredictResponse', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTRESPONSE,
  __module__ = 'clipper_frontend_pb2'
  # @@protoc_insertion_point(class_scope:clipper.grpc.PredictResponse)
  ))
_sym_db.RegisterMessage(PredictResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class PredictStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.PredictFloats = channel.unary_unary(
          '/clipper.grpc.Predict/PredictFloats',
          request_serializer=PredictRequest.SerializeToString,
          response_deserializer=PredictResponse.FromString,
          )


  class PredictServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def PredictFloats(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_PredictServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'PredictFloats': grpc.unary_unary_rpc_method_handler(
            servicer.PredictFloats,
            request_deserializer=PredictRequest.FromString,
            response_serializer=PredictResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'clipper.grpc.Predict', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaPredictServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def PredictFloats(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaPredictStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def PredictFloats(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    PredictFloats.future = None


  def beta_create_Predict_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('clipper.grpc.Predict', 'PredictFloats'): PredictRequest.FromString,
    }
    response_serializers = {
      ('clipper.grpc.Predict', 'PredictFloats'): PredictResponse.SerializeToString,
    }
    method_implementations = {
      ('clipper.grpc.Predict', 'PredictFloats'): face_utilities.unary_unary_inline(servicer.PredictFloats),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Predict_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('clipper.grpc.Predict', 'PredictFloats'): PredictRequest.SerializeToString,
    }
    response_deserializers = {
      ('clipper.grpc.Predict', 'PredictFloats'): PredictResponse.FromString,
    }
    cardinalities = {
      'PredictFloats': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'clipper.grpc.Predict', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
